"""empty message

Revision ID: 72f53806089c
Revises: 300f416217f5
Create Date: 2020-09-04 14:01:06.424776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72f53806089c'
down_revision = '300f416217f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('facility_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['facility_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'facility_id')
    # ### end Alembic commands ###
