"""empty message

Revision ID: baac02801c98
Revises: 72f53806089c
Create Date: 2020-09-04 14:02:42.945041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baac02801c98'
down_revision = '72f53806089c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('facilityname', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=128), nullable=False),
    sa.Column('county', sa.String(length=128), nullable=False),
    sa.Column('ward', sa.String(length=128), nullable=False),
    sa.Column('sublocation', sa.String(length=128), nullable=True),
    sa.Column('town', sa.String(length=128), nullable=True),
    sa.Column('landmark', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ward')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facility')
    # ### end Alembic commands ###
