"""empty message

Revision ID: c1f98a36103b
Revises: 94dd07ea119f
Create Date: 2020-09-08 19:06:43.686035

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1f98a36103b'
down_revision = '94dd07ea119f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('teamname', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('facility_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], name='teams_facility_id_fkey'),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], name='teams_provider_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='teams_pkey')
    )
    # ### end Alembic commands ###
