"""empty message

Revision ID: e37a2046b76b
Revises: baac02801c98
Create Date: 2020-09-04 16:08:08.985531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37a2046b76b'
down_revision = 'baac02801c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_facility_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'facility', ['facility_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_facility_id_fkey', 'users', 'users', ['facility_id'], ['id'])
    # ### end Alembic commands ###
